# Generated by Django 2.1.15 on 2020-12-09 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_coviddata'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalHelp',
            fields=[
                ('request_id', models.AutoField(db_column='MID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('contact_number', models.IntegerField()),
                ('notes', models.CharField(max_length=150)),
            ],
        ),
    ]
